blank_issues_enabled: true
contact_links:
  - name: Questions and Community
    url: https://github.com/ItsMrCodeX/HellDivers2-Stratagem-Deck/discussions
    about: For questions, general feedback, or discussion, please use Discussions.
