blank_issues_enabled: true
contact_links:
  - name: Questions and Community
    url: https://github.com/STiben/HD2-Companion/discussions
    about: For questions, general feedback, or discussion, please use Discussions.
